export const ENDPOINTS = {
  auth: {
    login: '/auth/login',
    register: '/auth/register-company',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    me: '/auth/me',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    changePassword: '/auth/change-password',
    verifyEmail: '/auth/verify-email',
    resendVerification: '/auth/resend-verification',
  },
  dashboard: {
    overview: '/dashboard/overview',
    revenueTrend: '/dashboard/revenue-trend',
    statusBreakdown: '/dashboard/invoice-status-breakdown',
    payrollTrend: '/dashboard/payroll-trend',
    outstandingClients: '/dashboard/outstanding-clients',
    financialSummary: '/dashboard/financial-summary',
    reportExport: '/dashboard/report/export',
  },
  invoices: {
    list: '/invoices',
    create: '/invoices',
    detail: (id: string) => `/invoices/${id}`,
    update: (id: string) => `/invoices/${id}`,
    remove: (id: string) => `/invoices/${id}`,
    cancel: (id: string) => `/invoices/${id}/cancel`,
    send: (id: string) => `/invoices/${id}/send`,
    recordPayment: (id: string) => `/invoices/${id}/record-payment`,
    pdf: (id: string) => `/invoices/${id}/pdf`,
    publicShare: (token: string) => `/invoices/public/${token}`,
    publicSharePdf: (token: string) => `/invoices/public/${token}/pdf`,
  },
  invoiceTemplates: {
    list: '/invoice-templates',
    create: '/invoice-templates',
    detail: (id: string) => `/invoice-templates/${id}`,
    update: (id: string) => `/invoice-templates/${id}`,
    remove: (id: string) => `/invoice-templates/${id}`,
    clone: (id: string) => `/invoice-templates/${id}/clone`,
    setDefault: (id: string) => `/invoice-templates/${id}/set-default`,
    preview: '/invoice-templates/preview',
  },
  clients: {
    list: '/clients',
    create: '/clients',
    detail: (id: string) => `/clients/${id}`,
    update: (id: string) => `/clients/${id}`,
    remove: (id: string) => `/clients/${id}`,
    invoices: (id: string) => `/clients/${id}/invoices`,
  },
  employees: {
    list: '/employees',
    create: '/employees',
    detail: (id: string) => `/employees/${id}`,
    update: (id: string) => `/employees/${id}`,
    remove: (id: string) => `/employees/${id}`,
    salarySlips: (id: string) => `/employees/${id}/salary-slips`,
    avatar: (id: string) => `/employees/${id}/avatar`,
  },
  departments: {
    list: '/departments',
    create: '/departments',
    detail: (id: string) => `/departments/${id}`,
    update: (id: string) => `/departments/${id}`,
    remove: (id: string) => `/departments/${id}`,
  },
  salaryStructures: {
    list: '/salary-structures',
    create: '/salary-structures',
    detail: (id: string) => `/salary-structures/${id}`,
    update: (id: string) => `/salary-structures/${id}`,
    remove: (id: string) => `/salary-structures/${id}`,
  },
  payroll: {
    list: '/payroll',
    process: '/payroll/process',
    detail: (id: string) => `/payroll/${id}`,
    slips: (id: string) => `/payroll/${id}/slips`,
    finalize: (id: string) => `/payroll/${id}/finalize`,
    remove: (id: string) => `/payroll/${id}`,
    reports: '/payroll/reports/summary',
  },
  salarySlips: {
    list: '/salary-slips',
    detail: (id: string) => `/salary-slips/${id}`,
    markPaid: (id: string) => `/salary-slips/${id}/mark-paid`,
    pdf: (id: string) => `/salary-slips/${id}/pdf`,
  },
  users: {
    list: '/users',
    create: '/users',
    detail: (id: string) => `/users/${id}`,
    update: (id: string) => `/users/${id}`,
    remove: (id: string) => `/users/${id}`,
  },
  auditLogs: {
    list: '/audit-logs',
    actions: '/audit-logs/actions',
  },
  taxRates: {
    list: '/tax-rates',
    create: '/tax-rates',
    update: (id: string) => `/tax-rates/${id}`,
    remove: (id: string) => `/tax-rates/${id}`,
  },
  company: {
    me: '/company/me',
    setup: '/company/setup',
    logo: '/company/logo',
    invoiceSettings: '/company/invoice-settings',
    payrollSettings: '/company/payroll-settings',
  },
} as const;
