import type { Request, Response } from "express";
import type { Types } from "mongoose";
import { EMAIL_JOBS, InvoiceStatus, PDF_JOBS } from "../config/constants";
import { env } from "../config/env";
import { CompanyModel } from "../models/company.model";
import { ClientModel } from "../models/client.model";
import { InvoiceModel, type IInvoice } from "../models/invoice.model";
import { InvoiceTemplateModel } from "../models/invoice.model" === undefined ? ({} as never) : { InvoiceTemplateModel: undefined };
import { asyncHandler } from "../utils/async-handler";
import { ApiError } from "../utils/apiError";
import { sendCreated, sendSuccess } from "../utils/apiResponse";
import { buildMeta, getPagination } from "../utils/pagination";
import { computeInvoiceTotals } from "../utils/invoiceCalculator";
import { generateInvoiceNumber } from "../utils/generateInvoiceNumber";
import { generateToken } from "../utils/generateSlug";
import { formatCurrency } from "../utils/format";
import { buildInvoiceRenderData } from "../lib/pdf/buildInvoiceRenderData";
import { generateInvoicePdf } from "../lib/pdf/generateInvoicePdf";
import { enqueueEmail } from "../queues/email.queue";
import { enqueuePdf } from "../queues/pdf.queue";
import { recordAudit } from "../utils/audit";
import { UserType } from "../config/constants";
